#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# symlink settings in
cd "$HOME/Library/Application Support/Sublime Text 2"

ln -s "$HOME/.dotfiles/sublime2/Packages" "Packages"
ln -s "$HOME/.dotfiles/sublime2/Installed Packages" "Installed Packages"
ln -s "$HOME/.dotfiles/sublime2/Pristine Packages" "Pristine Packages"
