#!/bin/bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"

set -e

echo ''

info () {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

link_files () {
    ln -s "$1" "$2"
    success "linked $1 to $2"
}

install_sublime () {

    sublime2_dir="$HOME/Library/Application Support/Sublime Text 2"

    if [ -d "$sublime2_dir" ]; then

        info 'replacing sublime packages with symlinks'

        user "Replace existing Sublime packages with these ones? [y]es, [n]o"
        read -n 1 action

        case "$action" in
            y )
                overwrite=true;;
            * )
                overwrite=false;;
        esac

        if [ "$overwrite" == "true" ]
        then

            source="$DOTFILES_ROOT/sublime2"
            rm -rf "$sublime2_dir/Packages" "$sublime2_dir/Installed Packages" "$sublime2_dir/Pristine Packages"
            link_files "$source/Packages" "$sublime2_dir/Packages"
            link_files "$source/Installed Packages" "$sublime2_dir/Installed Packages"
            link_files "$source/Pristine Packages" "$sublime2_dir/Pristine Packages"
        else
            success "didn't overwrite sublime packages"
        fi

        subl_cli="/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl"
        if   [ -f "$subl_cli" ]; then
            info "linking subl cli binary"
            link_files "$subl_cli" "$HOME/.dotfiles/sublime2/bin/subl"
        fi

    else
        info "not installing Sublime because it's not there"
    fi
}

install_dotfiles () {
    info 'installing dotfiles'

    overwrite_all=false
    backup_all=false
    skip_all=false

    for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
    do
        dest="$HOME/.`basename \"${source%.*}\"`"

        if [ -f $dest ] || [ -d $dest ]
        then

            overwrite=false
            backup=false
            skip=false

            if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
            then
                user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
                read -n 1 action

                case "$action" in
                    o )
                        overwrite=true;;
                    O )
                        overwrite_all=true;;
                    b )
                        backup=true;;
                    B )
                        backup_all=true;;
                    s )
                        skip=true;;
                    S )
                        skip_all=true;;
                    * )
                        ;;
                esac
            fi

            if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
            then
                rm -rf $dest
                success "removed $dest"
            fi

            if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
            then
                mv $dest $dest\.backup
                success "moved $dest to $dest.backup"
            fi

            if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
            then
                link_files $source $dest
            else
                success "skipped $source"
            fi

        else
            link_files $source $dest
        fi

    done
}

install_dotfiles
install_sublime

echo ''
echo '  All installed!'
